CREATE DATABASE IF NOT EXISTS StyleSync;
USE StyleSync;

CREATE TABLE IF NOT EXISTS USER_Details (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255)
);

show DATABASES;